#!/bin/bash

echo Setting monitor placement
xrandr --output HDMI-1 --auto --left eDP-1

if [ $? == 0 ]; then
    echo "OK"
fi

echo mapping ESC to Caplocks
map-esc-to-caps.sh

echo Activate SSH
ssh-add

echo Activating WiFi
wifi

echo "Completed"

