#!/bin/bash

echo Setting monitor placement
xrandr --output HDMI-1 --auto --above eDP-1

if [ $? == 0 ]; then
    echo "OK"
fi

echo mapping ESC to Caplocks
map-esc-to-caps.sh

echo Activate SSH
ssh-add

echo Stopping Apache server
service apache2 stop

echo Stopping Mysql daemon
service mysql stop

echo Activating WiFi
wifi

echo "Completed"

