#!/bin/bash

echo Setting monitor placement
xrandr --output HDMI-1 --auto --above eDP-1

if [ $? == 0 ]; then
    echo "OK"
fi

echo mapping ESC to Caplocks
map-esc-to-caps.sh

echo Activating WiFi
wifi
nmtui-connect

echo "Completed"

